server:
  port: 8801
spring:
  datasource:
    url: jdbc:mysql://localhost:3316/newdb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  type-aliases-package: com.maple.springtest.demo.entity
  mapper-locations: classpath:mapper/*Mapper.xml

logging:
  level:
    com:
      maple:
        springtest:
          demo:
            mapper: debug
            controller: info